name: Build and deploy

on: 
  push:
  schedule:
    - cron: 0 4 * * *

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and deploy
      run: |
        npm install
        npm run ci
      env:
        CI: true
        WEBMENTION_IO_TOKEN: ${{ secrets.WEBMENTION_IO_TOKEN }}
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
